// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "04DoTASOyLPK4L3pCXWDdssSYIvVVbDVqDGsJwg9zRAIPbAosqz7QtgXxg7MxW10DjIWGk";
}
}
}

